// frontend/src/components/common/LiquidGlassPanel.vue
<script setup lang="ts">
  import { computed, ref } from 'vue'
  import { useUIStore } from '../../stores/ui'
  import { useLiquidGlass } from '../../composables/useLiquidGlass'

  const props = withDefaults(
    defineProps<{
      as?: string
      active?: boolean
      interactive?: boolean
      hoverEffect?: 'none' | 'glow' | 'scale' | 'all'
      radius?: string
      fallbackClass?: string
      baseColorClass?: string
      disabled?: boolean
    }>(),
    {
      as: 'div',
      active: true,
      interactive: false,
      hoverEffect: 'none',
      radius: 'rounded-[var(--radius-squircle-md)]',
      fallbackClass: '',
      baseColorClass: 'bg-[var(--app-liquid-glass-bg)]',
      disabled: false,
    },
  )

  const uiStore = useUIStore()

  const isInteractive = computed(() => {
    return props.interactive && !props.disabled
  })

  // Refraction layer element — the composable registers/unregisters the SVG filter
  // automatically when this ref changes (e.g. effects toggle, active state change).
  const refractionLayer = ref<HTMLElement | null>(null)
  const { filterId } = useLiquidGlass(refractionLayer)
</script>

<template>
  <component
    :is="as"
    :disabled="props.disabled ? true : undefined"
    class="relative isolate transition-all duration-300 overflow-visible group/liquid"
    :class="[
      isInteractive ? 'cursor-pointer' : '',
      isInteractive &&
      uiStore.effects === 'full' &&
      (hoverEffect === 'all' || hoverEffect === 'scale')
        ? 'hover:scale-[1.02] active:scale-[0.98]'
        : '',
      radius,
      uiStore.effects === 'reduced' ? fallbackClass : '',
    ]"
  >
    <template v-if="uiStore.effects === 'full'">
      <!-- Layer 1: Central Translucency + Refraction (backdrop-filter → SVG SDF displacement) -->
      <div
        v-if="active"
        ref="refractionLayer"
        class="absolute top-0 left-0 -z-10 h-full w-full overflow-hidden transition-all duration-300 pointer-events-none"
        :class="[radius, baseColorClass]"
        :style="
          filterId
            ? { backdropFilter: `url(#${filterId})`, WebkitBackdropFilter: `url(#${filterId})` }
            : {}
        "
      >
        <!-- Interactive Hover Glow -->
        <div
          v-if="isInteractive && (hoverEffect === 'all' || hoverEffect === 'glow')"
          class="absolute inset-0 bg-gradient-to-t from-transparent to-white/20 dark:to-white/10 opacity-0 group-hover/liquid:opacity-100 transition-opacity duration-300 pointer-events-none"
        ></div>
      </div>
      <!-- Non-active interactive: transparent placeholder for hover reveal -->
      <div
        v-else-if="isInteractive"
        class="absolute top-0 left-0 -z-10 h-full w-full overflow-hidden transition-all duration-300 pointer-events-none bg-transparent opacity-0 group-hover/liquid:bg-[var(--app-liquid-glass-hover)] group-hover/liquid:opacity-100"
        :class="[radius]"
      ></div>

      <!-- Layer 2: Specular Bevel — inner sheen + inset shadows + outer drop shadow -->
      <div
        v-if="active"
        class="absolute inset-0 z-0 pointer-events-none transition-all duration-300 lg-bevel"
        :class="[radius]"
      ></div>

      <!-- Layer 2b: Hairline Specular Ring — conic-gradient masked border (bright top, dim bottom) -->
      <div
        v-if="active"
        class="absolute inset-0 z-[1] pointer-events-none transition-all duration-300 lg-specular"
        :class="[radius]"
      ></div>
    </template>
    <template v-else-if="!fallbackClass">
      <!-- Lightweight fallback for reduced mode -->
      <div
        class="absolute top-0 left-0 -z-10 h-full w-full overflow-hidden transition-all duration-300 pointer-events-none backdrop-blur-md"
        :class="[
          radius,
          active
            ? `${baseColorClass} opacity-100 border border-[var(--glass-border)]`
            : isInteractive
              ? 'bg-transparent opacity-0 group-hover:bg-[var(--app-liquid-glass-hover)]'
              : 'bg-transparent opacity-0',
        ]"
      ></div>
    </template>

    <!-- Content Slot Wrapper -->
    <div
      class="relative z-10 w-full h-full flex items-[inherit] justify-[inherit] flex-col-[inherit] flex-row-[inherit]"
    >
      <slot />
    </div>
  </component>
</template>

// extension/src/lib/glass/LiquidGlassPanel.svelte
<script lang="ts">
  import { useLiquidGlass, supportsUrlBackdropFilter } from './useLiquidGlass.svelte'

  let {
    as = 'div',
    active = true,
    interactive = false,
    hoverEffect = 'none',
    radius = 'var(--radius-squircle-md, 1.5rem)',
    fallbackClass = '',
    baseColor = 'var(--app-liquid-glass-bg, rgba(0,0,0,0.2))',
    disabled = false,
    effects = 'full',
    children,
    class: extraClass = '',
    onclick,
  }: {
    as?: string
    active?: boolean
    interactive?: boolean
    hoverEffect?: 'none' | 'glow' | 'scale' | 'all'
    radius?: string
    fallbackClass?: string
    baseColor?: string
    disabled?: boolean
    effects?: 'full' | 'reduced'
    children?: import('svelte').Snippet
    class?: string
    onclick?: (e: MouseEvent) => void
  } = $props()

  let layerEl = $state<HTMLElement | null>(null)

  let isInteractive = $derived(interactive && !disabled)
  let hasGlow = $derived(isInteractive && (hoverEffect === 'all' || hoverEffect === 'glow'))
  let hasScale = $derived(
    isInteractive && effects === 'full' && (hoverEffect === 'all' || hoverEffect === 'scale'),
  )

  const { filterId } = useLiquidGlass(() => layerEl)

  let backdropStyle = $derived.by(() => {
    if (!filterId || !supportsUrlBackdropFilter()) {
      return 'backdrop-filter: blur(2px) saturate(1.05); -webkit-backdrop-filter: blur(2px) saturate(1.05)'
    }
    return `backdrop-filter: url(#${filterId}); -webkit-backdrop-filter: url(#${filterId})`
  })
</script>

{#if as === 'button'}
  <button
    class="liquid-glass-root lg-group {extraClass}"
    style="border-radius: {radius}"
    class:lg-interactive={isInteractive}
    class:lg-scale={hasScale}
    {disabled}
    {onclick}
  >
    {#if effects === 'full' && active}
      <div
        bind:this={layerEl}
        class="liquid-glass-refraction"
        style="{backdropStyle}; border-radius: {radius}; background: {baseColor}"
      >
        {#if hasGlow}
          <div class="liquid-glass-glow"></div>
        {/if}
      </div>
    {:else if effects === 'full' && isInteractive}
      <div class="liquid-glass-placeholder" style="border-radius: {radius}"></div>
    {:else if effects === 'reduced' && !fallbackClass}
      <div
        class="liquid-glass-fallback"
        class:lg-fallback-active={active}
        style="border-radius: {radius}; background: {baseColor}"
      ></div>
    {/if}

    {#if effects === 'full' && active}
      <div class="lg-bevel" style="border-radius: {radius}"></div>
      <div class="lg-specular" style="border-radius: {radius}"></div>
    {/if}

    <div class="liquid-glass-content">
      {@render children?.()}
    </div>
  </button>
{:else}
  <div
    class="liquid-glass-root lg-group {extraClass}"
    style="border-radius: {radius}"
    class:lg-interactive={isInteractive}
    class:lg-scale={hasScale}
  >
    {#if effects === 'full' && active}
      <div
        bind:this={layerEl}
        class="liquid-glass-refraction"
        style="{backdropStyle}; border-radius: {radius}; background: {baseColor}"
      >
        {#if hasGlow}
          <div class="liquid-glass-glow"></div>
        {/if}
      </div>
    {:else if effects === 'full' && isInteractive}
      <div class="liquid-glass-placeholder" style="border-radius: {radius}"></div>
    {:else if effects === 'reduced' && !fallbackClass}
      <div
        class="liquid-glass-fallback"
        class:lg-fallback-active={active}
        style="border-radius: {radius}; background: {baseColor}"
      ></div>
    {/if}

    {#if effects === 'full' && active}
      <div class="lg-bevel" style="border-radius: {radius}"></div>
      <div class="lg-specular" style="border-radius: {radius}"></div>
    {/if}

    <div class="liquid-glass-content">
      {@render children?.()}
    </div>
  </div>
{/if}
